// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAB2w7LUmAP0lCSka5UUN0Qvh1k1oIbwE',
    appId: '1:359880053496:web:34e2ef686e3d23a700610d',
    messagingSenderId: '359880053496',
    projectId: 'mentallance',
    authDomain: 'mentallance.firebaseapp.com',
    storageBucket: 'mentallance.appspot.com',
    measurementId: 'G-4JNEH3BDNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxUtkhnPx8_gCmw5yYw75rpCDSh4bd7-A',
    appId: '1:359880053496:android:e14ff6666ee7053300610d',
    messagingSenderId: '359880053496',
    projectId: 'mentallance',
    storageBucket: 'mentallance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrE1E1PyDYc9RBzsKREncLRPQdF5WS6NQ',
    appId: '1:359880053496:ios:3b227d40f88b68ca00610d',
    messagingSenderId: '359880053496',
    projectId: 'mentallance',
    storageBucket: 'mentallance.appspot.com',
    iosClientId: '359880053496-cvh7dbl77n0b5umk91m3gc073j17fekv.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentallance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrE1E1PyDYc9RBzsKREncLRPQdF5WS6NQ',
    appId: '1:359880053496:ios:04fa3124e1a1d29f00610d',
    messagingSenderId: '359880053496',
    projectId: 'mentallance',
    storageBucket: 'mentallance.appspot.com',
    iosClientId: '359880053496-94ncnhubncbvp1kc76o0sklk2k1ubfdg.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentallance.RunnerTests',
  );
}
